version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quiz
    volumes:
      - ./init-config.sql:/docker-entrypoint-initdb.d/init-config.sql
    ports:
      - 5432:5432

